#!/bin/sh

# Copyright © 2017-2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage()
{
    printf 'Usage: %s KEYID [YEAR]\n' "${0##*/}"
}

export TZ=Etc/GMT-12

if [ $# -eq 1 ] && { [ "$1" = '-h' ] || [ "$1" = '--help' ]; }
then
    usage
    exit
elif [ $# -eq 0 ] || [ $# -gt 2 ]
then
    usage >&2
    exit 1
fi
keyid="$1"
if [ $# -eq 1 ]
then
    year=$(date '+%Y')
    year=$((year + 1))
else
    year="$2"
fi
exec faketime -f "$((year - 1))-10-01 12:00:00" gpg --quick-set-expire "$keyid" "$((year + 1))-01-01"

# vim:ts=4 sts=4 sw=4 et
