#!/bin/sh

set -e -u

for addr in "$@"
do
    user=${addr%@*}
    host=${addr##*@}
    printf 'https://%s/.well-known/openpgpkey/hu/' "$host"
    printf '%s' "$user" \
    | tr '[:upper:]' '[:lower:]' \
    | openssl sha1 -binary \
    | base32 \
    | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567' \
         'ybndrfg8ejkmcpqxot1uwisza345h769'
done

# vim:ts=4 sts=4 sw=4 et
