#!/bin/sh

# Copyright © 2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage()
{
    printf 'Usage: %s ADDRESS [ADDRESS...]\n' "${0#**/}"
}

if [ $# -eq 0 ] || ( [ "${1#-}" != "$1" ] && [ "${1#*@}" = "${1}" ] )
then
    usage >&2
    exit 1
elif [ "$1" = '-h' ] || [ "$1" = '--help' ]
then
    usage
    exit
fi

for addr in "$@"
do
    user=${addr%@*}
    host=${addr##*@}
    printf 'https://%s/.well-known/openpgpkey/hu/' "$host"
    printf '%s' "$user" \
    | tr '[:upper:]' '[:lower:]' \
    | openssl sha1 -binary \
    | base32 \
    | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567' \
         'ybndrfg8ejkmcpqxot1uwisza345h769'
done

# vim:ts=4 sts=4 sw=4 et
