name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: run tests
      run: |
        prove -v
    - name: run shellcheck
      run: |
        shellcheck *-*

# vim:ts=2 sts=2 sw=2 et
